image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci
  SERVER_ADDRESS: ec2-user@18.220.58.155

stages:
  - build
  - pushing
  - deploy



push-github:
  image: sombralibre/gitclient
  stage: pushing
  script: 
  - git remote set-url origin https://$GIT_ACCOUNT:$GIT_CREDENTIAL@github.com/NoSchool2K20/1BackGesCours.git
  - git stash 
  - git pull origin master --rebase
  - git stash pop
  - git add .
  - git commit -m "new feature integrate by gitlab ci"
  - git push origin master

deploy-prod:
  image: rastasheep/ubuntu-sshd
  stage: deploy
  script:
  - chmod 600 ../1backgestioncours.tmp/PROD_PEM
  - ssh -i $PROD_PEM -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $SERVER_ADDRESS './start.sh'
  only:
  - master
