image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci
  TEST_SERVER_ADDRESS: ec2-user@35.180.174.135
  SERVER_ADDRESS: ec2-user@18.220.58.155

stages:
  - build
  - testdeploy
  - test
  - deploy

back-build:
  image: trion/ng-cli
  stage: build
  script: "npm install && npm run build"

deploy-preprod:
  image: rastasheep/ubuntu-sshd
  stage: testdeploy
  script:
  - chmod 600 ../1backgestioncours.tmp/PPROD_PEM
  - ssh -i $PPROD_PEM -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $TEST_SERVER_ADDRESS './start.sh'
  only:
  - master

back-test-integration:
  image: 
    name: postman/newman
    entrypoint: [""]
  stage: test
  script: 
  - newman --version
  - npm install -g newman-reporter-html
  - newman run test/qsi_test_inte_local.postman_collection.json --reporters cli,html,junit --reporter-html-export report.html --reporter-junit-export report.xml
  artifacts:
    when: always
    paths:
    - report.html
    reports:
      junit: report.xml
  only:
  - master

push-github:
  image: sombralibre/gitclient
  stage: deploy
  script: 
  - git config --global user.email "deblock.adrien62@yahoo.fr"
  - git config --global user.name "Adrien deblock"
  - git remote set-url origin https://$GIT_ACCOUNT:$GIT_CREDENTIAL@github.com/NoSchool2K20/1BackGesCours.git
  - git push --force origin ${CI_COMMIT_SHA}:master
  only:
  - master

deploy-prod:
  image: rastasheep/ubuntu-sshd
  stage: deploy
  script:
  - chmod 600 ../1backgestioncours.tmp/PROD_PEM
  - ssh -i $PROD_PEM -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $SERVER_ADDRESS './start.sh'
  only:
  - master
