version: '3'
services:
  qsi-db:
    image: mysql:5
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_DATABASE: "qsi"

  qsi-back:
    build: .
    depends_on: 
      - qsi-db
    ports:
      - "9000:9000"
    environment:
      MYSQL_DB_HOST: qsi-db
      MYSQL_DB_HOST: "qsi"
      MYSQL_DB_PASSWORD: "admin"
      MYSQL_DB_PORT: 3306

