image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci
  DEV_SERVER_ADDRESS: ec2-user@18.220.58.155

stages:
  - build
  - deploy

build-back:
  image: trion/ng-cli
  stage: build
  script: "echo coucou"