image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci
  DEV_SERVER_ADDRESS: ec2-user@18.220.58.155

stages:
  - build
  - deploy

build-back:
  image: trion/ng-cli
  stage: build
  script: "npm install && npm run build"

deploy-prod:
  image: rastasheep/ubuntu-sshd
  stage: deploy
  script:
  - chmod 600 ../1backgestioncours.tmp/PROD_PEM
  - ssh -i $PROD_PEM -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $PROD_SERVER_ADDRESS './start.sh'
  only:
  - master

